project:
  type: book
  output-dir: docs
  
book:
  title: " "
  favicon: logo_white.png
  site-url: https://star-psych.github.io
  page-navigation: false
  
  sidebar: 
    style: docked
    background: light
    logo: logo_text.png
    title: ' '
    
  chapters:
    - index.qmd
    - part: "Preregistration"
      chapters: 
          - prereg-what.qmd
    - part: "Materials"
      chapters: 
        - materials-what.qmd
    - part: "Data"
      chapters: 
        - data-what.qmd
        - data-why.qmd
    - part: "Analysis scripts"
      chapters: 
        - analysis-what.qmd
    - summary.qmd

bibliography: references.bib
csl: apa-numeric-superscript.csl

format:
  html:
    theme: cosmo
    css: custom.css

    mainfont: "system-ui"
    number-sections: false
    page-layout: full
    toc-title: On this page
    title-block-style: none
    grid:
      sidebar-width: 350px
    



